### ISSUE TITLE
New Character Activity State

### ISSUE THREAD

**Issue by BrianAtwell** [parnesybb/DNDApp#20]
Once the character has been created possibly change the [Back Stack](https://developer.android.com/guide/components/tasks-and-back-stack.html) to skip to the main menu.

Also add a menu to go to:

- Main Menu
- Mode Main Menu (DM mode menu or player mode menu)
- Character creation steps (if character creation is started and did not finish)

**Comment by BrianAtwell** [comment]
Menu Toolbar created in Brian Toolbar Pull request

**Comment by parnesybb** [comment]
Issue with the toolbar on the character sheet screen.  Instead of navigating, it simply removes the option from the toolbar.

**Comment by BrianAtwell** [comment]
set to always call `return base.OnOptionsItemSelected(item);`
